[package]
name = "peas"
version = "0.1.0"
authors = ["Elliot Hillary <elliot@peers.net.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "*"
crow = "*"
specs-derive="*"